components:
  schemas:
    CreateProduct:
      type: object
      required:
        - title
        - price
        - category
        - stock
        - specifications
        - productImages
      properties:
        title:
          type: string
          example: "product"
        price:
          type: string
          example: "5000000"
        category:
          type: string
          example: "66ef1203b9e0421ff0e9d2e1"
        stock:
          type: string
          example: "10"
        discount:
          type: string
          example: "10"
        specifications:
          type: string
          example: "Specs here..."
        details:
          type: string
          example: "Details here..."
        productImages:
          type: array
          items:
            type: string
            format: binary
    UpdateProduct:
      type: object
      properties:
        title:
          type: string
          example: "product"
        price:
          type: string
          example: "5000000"
        category:
          type: string
          example: "66ef1203b9e0421ff0e9d2e1"
        stock:
          type: string
          example: "10"
        discount:
          type: string
          example: "10"
        specifications:
          type: string
          example: "Specs here..."
        details:
          type: string
          example: "Details here..."
        productImages:
          type: array
          items:
            type: string
            format: binary