paths:
  /admin/product/list:
    get:
      tags:
        - Admin => Product
      summary: Get list of products
      security:
        - BearerAuth: []
      parameters:
        - $ref: "#/components/parameters/PageNumber"
        - $ref: "#/components/parameters/PageSize"
      responses:
        "200":
          $ref: "#/components/responses/Success"
        "401":
          $ref: "#/components/responses/UnAuthorized"
        "403":
          $ref: "#/components/responses/NotAllowed"

  /admin/product:
    post:
      tags:
        - Admin => Product
      summary: Create a new products
      security:
        - BearerAuth: []
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/CreateProduct"
      responses:
        "201":
          $ref: "#/components/responses/Created"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/UnAuthorized"
        "403":
          $ref: "#/components/responses/NotAllowed"

  /admin/product/{id}:
    put:
      tags:
        - Admin => Product
      summary: Update existing products
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/UpdateProduct"
      responses:
        "200":
          $ref: "#/components/responses/Success"
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NotFound"
        "401":
          $ref: "#/components/responses/UnAuthorized"
        "403":
          $ref: "#/components/responses/NotAllowed"

    delete:
      tags:
        - Admin => Product
      summary: Delete products by id
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          $ref: "#/components/responses/Success"
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NotFound"
        "401":
          $ref: "#/components/responses/UnAuthorized"
        "403":
          $ref: "#/components/responses/NotAllowed"
    
    get:
      tags:
        - Admin => Product
      summary: Get product by id
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          $ref: "#/components/responses/Success"
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NotFound"
        "401":
          $ref: "#/components/responses/UnAuthorized"
        "403":
          $ref: "#/components/responses/NotAllowed"
